services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090 # HTTP
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - monitoramento
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana-provisining/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-provisining/dashboards:/etc/grafana/provisioning/dashboards
    ports:
     - '8080:3000'
    networks:
    - monitoramento
  aspnetgcmetrics:
    image: passarela/aspnetgcmetrics:0.2
    container_name: aspnetgcmetrics
    restart: unless-stopped
    ports:
     - '5000:80'
    networks:
    - monitoramento
  bombardier:
    image: alpine/bombardier
    command: -c 25 -d 1h -r 3000 -t 15s http://aspnetgcmetrics:80/api/simulate
    networks:
      - monitoramento
    depends_on:
      - aspnetgcmetrics
networks:
  monitoramento:
    name: monitoramento
    #external: true
